## Board-specific config for NXP FRDM i.MX93 board

IMX_SOC = imx93
ATF_PLATFORM ?= imx93
OPTEE_PLATFORM ?= imx-mx93evk
IMX_MKIMAGE_SOC ?= iMX93

UBOOT_APPLY_PATCHES ?=
# Set to 1 inside your config to use u-boot mainline
UBOOT_MAINLINE ?=

IMX_FW_VER = 8.32-1991416
IMX_FW_URL = https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-$(IMX_FW_VER).bin

ifeq ("$(UBOOT_MAINLINE)","1")
UBOOT_DEFCONFIG ?= imx93_frdm_defconfig
UBOOT_DEVICE_TREE ?= freescale/imx93-11x11-frdm
# SoC will skip mkimage (as our flash.bin will be generated by uboot's binman)

else
# Use NXP's U-Boot fork
UBOOT_GIT_URL ?= https://github.com/nxp-imx/uboot-imx.git
UBOOT_GIT_BRANCH ?= lf_v2026.04
# finally, support added in time for v2026.04
UBOOT_DEFCONFIG ?= imx93_11x11_frdm_defconfig
UBOOT_DEVICE_TREE ?= freescale/imx93-11x11-frdm
# we need to use the dreadful imx-mkimage...
IMX_OUT_FLASH_BIN ?= $(IMX_MKIMAGE_OUT_FLASH_BIN)
IMX_MKIMAGE_MK_TARGET ?= flash_singleboot
endif

UBOOT_EXTRA_CONFIG_FILES ?= $(MK_BOARD_SRC)/uboot/overrides.config \
							$(MK_BOARD_SRC)/uboot/usb-gadget.config
UBOOT_DEFAULT_ENV_FILE ?= $(MK_BOARD_SRC)/uboot/default.env

# Enable OP-TEE?
OPTEE_ENABLED ?=
# Memory configuration
TRUSTED_UART_BASE ?= 0x44380000
# allocate 32MB for TZDRAM, then 4MB for shared memory at the end of DRAM
OPTEE_TZDRAM_ADDR ?= 0xedc00000
OPTEE_TZDRAM_SIZE ?= 0x02000000
OPTEE_SHMEM_ADDR ?= 0xefc00000
OPTEE_SHMEM_SIZE ?= 0x00400000
OPTEE_TOTAL_SIZE ?= 0x02400000
OPTEE_DDR_SIZE = 0x80000000
OPTEE_MAKE_FLAGS_EXTRA ?= CFG_WITH_SOFTWARE_PRNG=y CFG_IMX_ELE=n

# Uses Linux mainline, so no need to override anything (except dts ofc)
KERNEL_DTS ?= arch/$(SOC_ARCH)/boot/dts/freescale/imx93-11x11-evk.dts

# Use the Linux FIT image generator snippet
#GEN_LINUX_FIT_INITRD_ENABLED ?= 1
GEN_LINUX_FIT_KERNEL_LOAD ?= 0x81000000
GEN_LINUX_FIT_FDT_LOAD ?= 0x85000000
GEN_LINUX_FIT_INITRD_LOAD ?= 0x85100000

# Buildroot config
BUILDROOT_EXTRA_CONFIG_FILES ?= $(MK_BOARD_SRC)/buildroot/default.config
BUILDROOT_EXTRA_CONFIG_FILES += \
		$(if $(OPTEE_ENABLED),$(MK_BOARD_SRC)/buildroot/optee.config)

# Disk image configuration: 2 parts
DISKIMG_PART_SCHEME ?= FDISK
DISKIMG_SIZE_SD ?= 1024M
DISKIMG_PART_SCRIPT_SD ?= $(PART_FDISK_1P_BOOT_FULL)
# only for ROOTFS on part 2: edit kernel bootargs
ifneq ("$(GEN_LINUX_FIT_INITRD_ENABLED)","1")
define DISKIMG_UBOOT_ENV_EMMC=
bootargs=console=ttyLP0,115200 earlycon,115200 root=/dev/mmcblk0p2 clk_ignore_unused
endef
endif

# Load SoC defaults
MK_SOC_DIR := $(MK_FRAMEWORK_LIB)/soc/$(IMX_SOC)
include $(MK_SOC_DIR)/soc_cfg.mk
