## Board-specific config for NXP FRDM i.MX93 board

IMX_SOC = imx93
ATF_PLATFORM ?= imx93
IMX_MKIMAGE_SOC ?= iMX93

UBOOT_APPLY_PATCHES ?=
# Set to 1 inside your config to use u-boot mainline
UBOOT_MAINLINE ?=

ifeq ("$(UBOOT_MAINLINE)","1")
UBOOT_DEFCONFIG ?= imx93_frdm_defconfig
UBOOT_DEVICE_TREE ?= imx93-11x11-frdm
# SoC will skip mkimage (as our flash.bin will be generated by uboot's binman)

else
# Use NXP's U-Boot fork (supports USB Gadget mode)
UBOOT_GIT_URL ?= https://github.com/nxp-imx/uboot-imx.git
UBOOT_GIT_BRANCH ?= lf_v2024.04
UBOOT_DEFCONFIG ?= imx93_11x11_frdm_defconfig
UBOOT_DEVICE_TREE ?= imx93-11x11-frdm
UBOOT_APPLY_PATCHES += $(MK_BOARD_SRC)/uboot/0002-imx-imx93_frdm-Add-basic-board-support.patch
# we need to use the dreadful imx-mkimage...
IMX_OUT_FLASH_BIN ?= $(IMX_MKIMAGE_OUT_FLASH_BIN)
IMX_MKIMAGE_MK_TARGET ?= flash_singleboot
endif

#UBOOT_EXTRA_CONFIG_FILES ?= $(MK_BOARD_SRC)/uboot/usb-gadget.config
#UBOOT_DEFAULT_ENV_FILE ?= $(MK_BOARD_SRC)/uboot/default.env

# Use Linux mainline
KERNEL_DTS ?= arch/$(SOC_ARCH)/boot/dts/freescale/imx93-11x11-evk.dts
#LINUX_UIMAGE_ITS ?= $(MK_BOARD_SRC)/linux-uimage.its

# Load RV1106 SoC defaults
MK_SOC_DIR := $(MK_FRAMEWORK_LIB)/soc/$(IMX_SOC)
include $(MK_SOC_DIR)/soc_cfg.mk
