## iMX firmware image build rules

IMX_MKIMAGE_DEST ?= $(BUILD_DEST)/imx-mkimage
IMX_MKIMAGE_GIT_URL ?= https://github.com/nxp-imx/imx-mkimage.git
IMX_MKIMAGE_BRANCH ?=

IMX_MKIMAGE_SOC ?= UNKNOWN_IMX_SOC
IMX_MKIMAGE_MK_TARGET ?= flash_evk
IMX_MKIMAGE_CFLAGS ?= -O2 -Wall -std=c99
IMX_MKIMAGE_FLAGS ?= SOC=$(IMX_MKIMAGE_SOC) dtbs=$(notdir $(UBOOT_DTB_FULL)) \
				$(IMX_MKIMAGE_OPTEE_FLAGS) CFLAGS="$(IMX_MKIMAGE_CFLAGS)"
IMX_MKIMAGE_FIRMWARE_DEST = $(IMX_MKIMAGE_DEST)/$(IMX_MKIMAGE_SOC)
IMX_MKIMAGE_OUT_FLASH_BIN = $(IMX_MKIMAGE_FIRMWARE_DEST)/flash.bin
# generic source for flash.bin (can also be generated by u-boot using binman)
IMX_OUT_FLASH_BIN ?= $(IMX_MKIMAGE_OUT_FLASH_BIN)

# op-tee integration
IMX_MKIMAGE_OPTEE_FLAGS ?= $(if $(OPTEE_ENABLED),TEE_LOAD_ADDR=$(OPTEE_TZDRAM_ADDR))
IMX_MKIMAGE_OPTEE_DEPS ?= $(if $(OPTEE_ENABLED),\
					  $(OPTEE_OUT_BIN),\
					  $(IMX_MKIMAGE_FIRMWARE_DEST)/.op-tee-deleted)

_IMX_UBOOT_COPY_FILES = $(UBOOT_OUT_SPL_BIN) $(UBOOT_OUT_NODTB_BIN) $(UBOOT_DTB_FULL)
_IMX_UBOOT_FILENAMES=$(notdir $(_IMX_UBOOT_COPY_FILES))
_IMX_MKIMAGE_TARGET := $(IMX_MKIMAGE_FIRMWARE_DEST)/.mkimage-files-copied

.PHONY: imx_mkimage
imx_mkimage: $(IMX_MKIMAGE_OUT_FLASH_BIN)
$(IMX_MKIMAGE_OUT_FLASH_BIN): $(_IMX_MKIMAGE_TARGET) $(IMX_MKIMAGE_DEST)/.git
	make -C $(IMX_MKIMAGE_DEST) $(IMX_MKIMAGE_FLAGS) $(IMX_MKIMAGE_MK_TARGET)

$(IMX_MKIMAGE_DEST)/.git:
	$(call mk_git_clone,$(IMX_MKIMAGE_GIT_URL),$(IMX_MKIMAGE_DEST),$(IMX_MKIMAGE_GIT_BRANCH))

# op-tee integration script
_IMX_MKIMAGE_OPTEE_SCRIPT = \
		$(if $(OPTEE_ENABLED),\
			rm -f "$(IMX_MKIMAGE_FIRMWARE_DEST)/.op-tee-deleted" && \
			cp -f "$(OPTEE_OUT_BIN)" "$(IMX_MKIMAGE_FIRMWARE_DEST)/tee.bin")

# dummy target which copies all required files to imx-mkimage dir
$(_IMX_MKIMAGE_TARGET): $(IMX_FIRMWARE_FILES_FULL) $(IMX_SENTINEL_FILES_FULL) \
		$(_IMX_UBOOT_COPY_FILES) $(ATF_BIN_FULL) \
		$(IMX_MKIMAGE_OPTEE_DEPS) $(UBOOT_MKIMAGE_BIN) | $(IMX_MKIMAGE_DEST)/.git
	# copy files to the imx-mkimage/<SOC> dir
	cp -f $(filter-out $(UBOOT_MKIMAGE_BIN),\
		$(filter-out %/.op-tee-deleted,$^)) "$(IMX_MKIMAGE_FIRMWARE_DEST)/"
	# mkimage needs to be renamed to mkimage_uboot at the destination
	cp -f "$(UBOOT_MKIMAGE_BIN)" "$(IMX_MKIMAGE_FIRMWARE_DEST)/mkimage_uboot";
	$(_IMX_MKIMAGE_OPTEE_SCRIPT)
	touch "$@"
	ls -l "$(IMX_MKIMAGE_FIRMWARE_DEST)"

$(IMX_MKIMAGE_FIRMWARE_DEST)/.op-tee-deleted: $(IMX_MKIMAGE_DEST)/.git
	rm -f "$(IMX_MKIMAGE_FIRMWARE_DEST)/tee.bin"
	touch "$@"

imx_mkimage_clean:
	rm -f "$(_IMX_MKIMAGE_TARGET)"
	$(MAKE) -C $(IMX_MKIMAGE_DEST) clean 

all: imx_mkimage
clean_all: imx_mkimage_clean

# iMX SPL image bootloader upload target 
.PHONY: imx_upload_spl
imx_upload_spl: $(UUU)
	$(UUU) -b spl $(IMX_OUT_FLASH_BIN)

